# 自定义参数属性
com:
  wnspace:
    blog:
      name: 程序员
      title: Spring Boot教程
      desc: ${com.wnspace.blog.name}正在努力写《${com.wnspace.blog.title}》

      # 随机字符串
      value: ${random.value}
      # 随机int
      number: ${random.int}
      # 随机long
      bignumber: ${random.long}
      # 10以内的随机数
      test1: ${random.int(10)}
      # 10-20之间的随机数
      test2: ${random.int[10, 20]}

# 设置开发环境
spring:
  profiles:
    active: dev

# 设置端口
server:
  port: 8080